### ISSUE TITLE
Problem with importing __docs__ 

### ISSUE THREAD

**Issue by ghost** [mjszczep/PyStasm#5]
Hello, I have this problem with both Python3.4 and Python2.7. Could you please help me out?

`Traceback (most recent call last):
  File "/home/student/PycharmProjects/CS161_Computer_Vision/Pankratov_Nikita_assignment_7.py", line 4, in <module>
    import stasm
  File "/usr/local/lib/python3.4/dist-packages/PyStasm-0.3.2-py3.4-linux-x86_64.egg/stasm/__init__.py", line 4, in <module>
    from ._stasm import __doc__
ImportError: /usr/local/lib/python3.4/dist-packages/PyStasm-0.3.2-py3.4-linux-x86_64.egg/stasm/_stasm.cpython-34m.so: undefined symbol: _ZTVN2cv11_InputArrayE`

**Comment by wandonye** [comment]
same here

**Comment by Tracyxzh** [comment]
same here

**Comment by abhudev** [comment]
I also have a very similar error, the undefined symbol is _ZN2cv5errorEiRKNS_6StringEPKcS4_i
(System - Ubuntu 16.04, OpenCV 3.2.0)

**Comment by kaashmonee** [comment]
Got the same problem, is there a fix?

**Comment by abhudev** [comment]
I didn't really explore it further, had to make do with other alternatives (for a deadline :P)

**Comment by mrlinyj** [comment]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lyj\Anaconda3\envs\py35\lib\site-packages\stasm\__init__.py", line 4, in <module>
    from ._stasm import __doc__
ImportError: DLL load failed: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lyj\Anaconda3\envs\py35\lib\site-packages\stasm\__init__.py", line 4, in <module>
    from ._stasm import __doc__
ImportError: DLL load failed: 找不到指定的模块。
